version: "3.9"
networks:
  mongo:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24
services:
  mongo:
    image: mongo:6.0.2
    container_name: mongo
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./mongo/volume:/data/db
      - ./mongo/scripts/:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    networks:
      mongo:
        ipv4_address: 172.22.0.2
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
      - ME_CONFIG_MONGODB_AUTH_DATABASE=${MONGO_INITDB_DATABASE}
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${DATABASE_USER}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${DATABASE_PASSWORD}
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      - ME_CONFIG_MONGODB_SERVER=${MONGO_HOST}
      - ME_CONFIG_REQUEST_SIZE=${ME_CONFIG_REQUEST_SIZE}
    links:
      - mongo
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - 8081:8081
    networks:
      mongo:
        ipv4_address: 172.22.0.3
  backend:
    image: backend:latest
    build: ./backend
    container_name: backend
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 8500:8500
    networks:
      mongo:
        ipv4_address: 172.22.0.4
