name: Integration Test CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Employee Service CI
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [18.12.1]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Compose Run Mongo
        run: docker-compose -f "docker-compose.yml" run -p 27017:27017 --name mongo -v ./mongo/dev-volume:/data/db -v ./mongo/docker-scripts/:/docker-entrypoint-initdb.d -d mongo

      - name: Compose Run Integration Tests
        run: docker-compose -f "docker-compose.yml" run -p 8500:8500 --name backend backend

      - name: Stop Containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down