name: Integration Test CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Employee Service CI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: backend

    strategy:
      matrix:
        node-version: [18.12.1]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: actions/setup-node@v3
      - run: npm ci

      - name: Run Compose Build Environment
        working-directory: ./
        run: docker-compose -f "docker-compose.yml" up

      - name: Wait For Compose Build Environment Up
        run: sleep 120s
        shell: bash

      - name: Wait For Compose Build Environment Up
        working-directory: backend
        run: npm run test:ci

      - name: Stop Containers
        if: always()
        working-directory: ./
        run: docker-compose -f "docker-compose.yml" down